apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ritikrpati23032003/kubernetes-ingress-deployment.git
    targetRevision: main
    path: k8s-files
    directory:
      include: main.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
